// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ichthys/v1/datablock_service.proto

package ichthysv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileBlock represents one grouped file slice.
type FileBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	ColumnHeaders []string               `protobuf:"bytes,2,rep,name=column_headers,json=columnHeaders,proto3" json:"column_headers,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileBlock) Reset() {
	*x = FileBlock{}
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlock) ProtoMessage() {}

func (x *FileBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBlock.ProtoReflect.Descriptor instead.
func (*FileBlock) Descriptor() ([]byte, []int) {
	return file_ichthys_v1_datablock_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileBlock) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *FileBlock) GetColumnHeaders() []string {
	if x != nil {
		return x.ColumnHeaders
	}
	return nil
}

func (x *FileBlock) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Row represents one row within a FileBlock.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNumber     int32                  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	Cells         map[string]string      `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_ichthys_v1_datablock_service_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *Row) GetCells() map[string]string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// DataBlock is the top-level payload returned by the fetch path.
type DataBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Blocks        []*FileBlock           `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBlock) Reset() {
	*x = DataBlock{}
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock) ProtoMessage() {}

func (x *DataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlock.ProtoReflect.Descriptor instead.
func (*DataBlock) Descriptor() ([]byte, []int) {
	return file_ichthys_v1_datablock_service_proto_rawDescGZIP(), []int{2}
}

func (x *DataBlock) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataBlock) GetBlocks() []*FileBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// FetchDataBlockRequest asks for changes after a client timestamp.
type FetchDataBlockRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IfModifiedSince *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=if_modified_since,json=ifModifiedSince,proto3" json:"if_modified_since,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchDataBlockRequest) Reset() {
	*x = FetchDataBlockRequest{}
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataBlockRequest) ProtoMessage() {}

func (x *FetchDataBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataBlockRequest.ProtoReflect.Descriptor instead.
func (*FetchDataBlockRequest) Descriptor() ([]byte, []int) {
	return file_ichthys_v1_datablock_service_proto_rawDescGZIP(), []int{3}
}

func (x *FetchDataBlockRequest) GetIfModifiedSince() *timestamppb.Timestamp {
	if x != nil {
		return x.IfModifiedSince
	}
	return nil
}

// FetchDataBlockResponse returns either a new DataBlock or a no-update marker.
type FetchDataBlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FetchDataBlockResponse_DataBlock
	//	*FetchDataBlockResponse_NoUpdate
	Payload       isFetchDataBlockResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataBlockResponse) Reset() {
	*x = FetchDataBlockResponse{}
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataBlockResponse) ProtoMessage() {}

func (x *FetchDataBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichthys_v1_datablock_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataBlockResponse.ProtoReflect.Descriptor instead.
func (*FetchDataBlockResponse) Descriptor() ([]byte, []int) {
	return file_ichthys_v1_datablock_service_proto_rawDescGZIP(), []int{4}
}

func (x *FetchDataBlockResponse) GetPayload() isFetchDataBlockResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchDataBlockResponse) GetDataBlock() *DataBlock {
	if x != nil {
		if x, ok := x.Payload.(*FetchDataBlockResponse_DataBlock); ok {
			return x.DataBlock
		}
	}
	return nil
}

func (x *FetchDataBlockResponse) GetNoUpdate() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Payload.(*FetchDataBlockResponse_NoUpdate); ok {
			return x.NoUpdate
		}
	}
	return nil
}

type isFetchDataBlockResponse_Payload interface {
	isFetchDataBlockResponse_Payload()
}

type FetchDataBlockResponse_DataBlock struct {
	DataBlock *DataBlock `protobuf:"bytes,1,opt,name=data_block,json=dataBlock,proto3,oneof"`
}

type FetchDataBlockResponse_NoUpdate struct {
	NoUpdate *emptypb.Empty `protobuf:"bytes,2,opt,name=no_update,json=noUpdate,proto3,oneof"`
}

func (*FetchDataBlockResponse_DataBlock) isFetchDataBlockResponse_Payload() {}

func (*FetchDataBlockResponse_NoUpdate) isFetchDataBlockResponse_Payload() {}

var File_ichthys_v1_datablock_service_proto protoreflect.FileDescriptor

const file_ichthys_v1_datablock_service_proto_rawDesc = "" +
	"\n" +
	"\"ichthys/v1/datablock_service.proto\x12\aichthys\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"o\n" +
	"\tFileBlock\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12%\n" +
	"\x0ecolumn_headers\x18\x02 \x03(\tR\rcolumnHeaders\x12 \n" +
	"\x04rows\x18\x03 \x03(\v2\f.ichthys.RowR\x04rows\"\x8d\x01\n" +
	"\x03Row\x12\x1d\n" +
	"\n" +
	"row_number\x18\x01 \x01(\x05R\trowNumber\x12-\n" +
	"\x05cells\x18\x02 \x03(\v2\x17.ichthys.Row.CellsEntryR\x05cells\x1a8\n" +
	"\n" +
	"CellsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\tDataBlock\x129\n" +
	"\n" +
	"updated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x06blocks\x18\x02 \x03(\v2\x12.ichthys.FileBlockR\x06blocks\"_\n" +
	"\x15FetchDataBlockRequest\x12F\n" +
	"\x11if_modified_since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fifModifiedSince\"\x8f\x01\n" +
	"\x16FetchDataBlockResponse\x123\n" +
	"\n" +
	"data_block\x18\x01 \x01(\v2\x12.ichthys.DataBlockH\x00R\tdataBlock\x125\n" +
	"\tno_update\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\bnoUpdateB\t\n" +
	"\apayload2e\n" +
	"\x10DataBlockService\x12Q\n" +
	"\x0eFetchDataBlock\x12\x1e.ichthys.FetchDataBlockRequest\x1a\x1f.ichthys.FetchDataBlockResponseB7Z5github.com/seoyhaein/tori/protos/ichthys/v1;ichthysv1b\x06proto3"

var (
	file_ichthys_v1_datablock_service_proto_rawDescOnce sync.Once
	file_ichthys_v1_datablock_service_proto_rawDescData []byte
)

func file_ichthys_v1_datablock_service_proto_rawDescGZIP() []byte {
	file_ichthys_v1_datablock_service_proto_rawDescOnce.Do(func() {
		file_ichthys_v1_datablock_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ichthys_v1_datablock_service_proto_rawDesc), len(file_ichthys_v1_datablock_service_proto_rawDesc)))
	})
	return file_ichthys_v1_datablock_service_proto_rawDescData
}

var file_ichthys_v1_datablock_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ichthys_v1_datablock_service_proto_goTypes = []any{
	(*FileBlock)(nil),              // 0: ichthys.FileBlock
	(*Row)(nil),                    // 1: ichthys.Row
	(*DataBlock)(nil),              // 2: ichthys.DataBlock
	(*FetchDataBlockRequest)(nil),  // 3: ichthys.FetchDataBlockRequest
	(*FetchDataBlockResponse)(nil), // 4: ichthys.FetchDataBlockResponse
	nil,                            // 5: ichthys.Row.CellsEntry
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_ichthys_v1_datablock_service_proto_depIdxs = []int32{
	1, // 0: ichthys.FileBlock.rows:type_name -> ichthys.Row
	5, // 1: ichthys.Row.cells:type_name -> ichthys.Row.CellsEntry
	6, // 2: ichthys.DataBlock.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: ichthys.DataBlock.blocks:type_name -> ichthys.FileBlock
	6, // 4: ichthys.FetchDataBlockRequest.if_modified_since:type_name -> google.protobuf.Timestamp
	2, // 5: ichthys.FetchDataBlockResponse.data_block:type_name -> ichthys.DataBlock
	7, // 6: ichthys.FetchDataBlockResponse.no_update:type_name -> google.protobuf.Empty
	3, // 7: ichthys.DataBlockService.FetchDataBlock:input_type -> ichthys.FetchDataBlockRequest
	4, // 8: ichthys.DataBlockService.FetchDataBlock:output_type -> ichthys.FetchDataBlockResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ichthys_v1_datablock_service_proto_init() }
func file_ichthys_v1_datablock_service_proto_init() {
	if File_ichthys_v1_datablock_service_proto != nil {
		return
	}
	file_ichthys_v1_datablock_service_proto_msgTypes[4].OneofWrappers = []any{
		(*FetchDataBlockResponse_DataBlock)(nil),
		(*FetchDataBlockResponse_NoUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ichthys_v1_datablock_service_proto_rawDesc), len(file_ichthys_v1_datablock_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ichthys_v1_datablock_service_proto_goTypes,
		DependencyIndexes: file_ichthys_v1_datablock_service_proto_depIdxs,
		MessageInfos:      file_ichthys_v1_datablock_service_proto_msgTypes,
	}.Build()
	File_ichthys_v1_datablock_service_proto = out.File
	file_ichthys_v1_datablock_service_proto_goTypes = nil
	file_ichthys_v1_datablock_service_proto_depIdxs = nil
}
