version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
